version: '3.8'

services:
  # Serviço base para construção, não será executado diretamente
  app:
    build: .
    image: basic-app  # Garante que usamos a imagem construída localmente

  # Atalho para o programa de tabuada
  tabuada:
    image: basic-app
    # O comando que será executado para este serviço
    command: br.com.basic.InputNomeIdade
    stdin_open: true # Equivalente ao -i do docker run
    tty: true        # Equivalente ao -t do docker run

  # Atalho para o programa de input de dados
  input:
    image: basic-app
    command: br.com.basic.Quadrado
    stdin_open: true
    tty: true

  # Atalho para o programa 3
  programa3:
    image: basic-app
    command: br.com.basic.Retangulo
    stdin_open: true
    tty: true

  # Atalho para o programa 4
  programa4:
    image: basic-app
    command: br.com.basic.DiferencaIdades
    stdin_open: true
    tty: true
